### ISSUE TITLE
Question about the prompt encoder of PT-Fewshot

### ISSUE THREAD

**Issue by ikm565** [THUDM/P-tuning#25]

**Comment by Xiao9905** [comment]
1. The use of prompt encoder is actually located in function `generate_default_inputs`:
https://github.com/THUDM/P-tuning/blob/413f26642b1f29bed03514eff4700e89346d668a/PT-Fewshot/pet/wrapper.py#L578-L598

2. Thanks for your reminder. This problem has been previously reported, and in fact we find it does not influence the results. But since it is confusing for many viewers, we have fixed it according to your advice.

**Comment by ikm565** [comment]
> 1. The use of prompt encoder is actually located in function `generate_default_inputs`:
>    https://github.com/THUDM/P-tuning/blob/413f26642b1f29bed03514eff4700e89346d668a/PT-Fewshot/pet/wrapper.py#L578-L598
> 2. Thanks for your reminder. This problem has been previously reported, and in fact we find it does not influence the results. But since it is confusing for many viewers, we have fixed it according to your advice.

thank you very much
