### ISSUE TITLE
multi-label classification

### ISSUE THREAD

**Issue by JaheimLee** [THUDM/P-tuning#9]
It's seems that P-tuning is not suitable for multi-label classification. Is it right? And if so, is it possible to expand P-tuning for those tasks?

**Comment by zheng-yanan** [comment]
> It's seems that P-tuning is not suitable for multi-label classification. Is it right? And if so, is it possible to expand P-tuning for those tasks?


Hi! Interesting topic. We did not experiment P-tuning on multi-label classification tasks. Since it is proved effective to use P-tuning on single-label classification tasks, it could be a solution that one considers transforming a multi-label classification task into multiple single-label classification tasks with P-tuning.

Thank you.
